name: í…ŒìŠ¤íŠ¸ ì»¤ë²„ë¦¬ì§€ í™•ì¸

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup JDk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test and Generate Coverage Report
        run: ./gradlew clean test jacocoTestReport

      - name: JaCoCo Report to PR
        uses: Madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.ACCESS_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: "ğŸ“Š Test Coverage Report"
          update-comment: true
          comment-mode: always

      - name: Upload jacoco HTML report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-report
          path: ${{ github.workspace }}/build/jacocoReport/test/html